import { IMasterDataEntityConfig } from '@core/interfaces/recruitment-management/master-data.interface';

export const MASTER_DATA_CONFIGS: Record<string, IMasterDataEntityConfig> = {
  country: {
    routeKey: 'country',
    apiPath: 'country',
    idField: 'countryId',
    title: 'Countries',
    singularLabel: 'Country',
    icon: 'fa-solid fa-earth-asia',
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, maxLength: 100 },
      { key: 'code', label: 'ISO Code', type: 'text', required: true, maxLength: 5, placeholder: 'e.g. BD' },
      {
        key: 'dialCode',
        label: 'Dial Code',
        type: 'text',
        required: true,
        maxLength: 10,
        placeholder: 'e.g. +880',
        pattern: '^\\+\\d{1,4}$',
        patternMessage: 'Dial code must be in the form +<digits>, e.g. +880.',
      },
    ],
  },
  'education-board': {
    routeKey: 'education-board',
    apiPath: 'education-board',
    idField: 'educationBoardId',
    title: 'Education Boards',
    singularLabel: 'Education Board',
    icon: 'fa-solid fa-landmark',
    fields: [
      { key: 'code', label: 'Code', type: 'text', required: true, maxLength: 10 },
      { key: 'name', label: 'Name', type: 'text', required: true, maxLength: 150 },
    ],
  },
  degree: {
    routeKey: 'degree',
    apiPath: 'degree',
    idField: 'degreeId',
    title: 'Degrees',
    singularLabel: 'Degree',
    icon: 'fa-solid fa-graduation-cap',
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, maxLength: 50, placeholder: 'e.g. SSC' },
      { key: 'fullName', label: 'Full Name', type: 'text', required: true, maxLength: 200, placeholder: 'e.g. Secondary School Certificate' },
      {
        key: 'position',
        label: 'Position (equivalence group)',
        type: 'number',
        required: true,
        placeholder: 'Degrees sharing a Position are treated as equivalent',
      },
    ],
  },
  university: {
    routeKey: 'university',
    apiPath: 'university-library',
    idField: 'universityLibraryItemId',
    title: 'Universities',
    singularLabel: 'University',
    icon: 'fa-solid fa-building-columns',
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true, maxLength: 200 },
      { key: 'code', label: 'Short Code', type: 'text', required: true, maxLength: 20, placeholder: 'e.g. DU' },
    ],
  },
  department: {
    routeKey: 'department',
    apiPath: 'department',
    idField: 'departmentId',
    title: 'Departments',
    singularLabel: 'Department',
    icon: 'fa-solid fa-building',
    fields: [{ key: 'name', label: 'Name', type: 'text', required: true, maxLength: 100 }],
  },
  gender: {
    routeKey: 'gender',
    apiPath: 'gender',
    idField: 'genderId',
    title: 'Genders',
    singularLabel: 'Gender',
    icon: 'fa-solid fa-venus-mars',
    fields: [{ key: 'name', label: 'Name', type: 'text', required: true, maxLength: 50 }],
  },
  'marital-status': {
    routeKey: 'marital-status',
    apiPath: 'marital-status',
    idField: 'maritalStatusId',
    title: 'Marital Statuses',
    singularLabel: 'Marital Status',
    icon: 'fa-solid fa-ring',
    fields: [{ key: 'name', label: 'Name', type: 'text', required: true, maxLength: 50 }],
  },
  religion: {
    routeKey: 'religion',
    apiPath: 'religion',
    idField: 'religionId',
    title: 'Religions',
    singularLabel: 'Religion',
    icon: 'fa-solid fa-place-of-worship',
    fields: [{ key: 'name', label: 'Name', type: 'text', required: true, maxLength: 50 }],
  },
  'blood-group': {
    routeKey: 'blood-group',
    apiPath: 'blood-group',
    idField: 'bloodGroupId',
    title: 'Blood Groups',
    singularLabel: 'Blood Group',
    icon: 'fa-solid fa-droplet',
    fields: [{ key: 'name', label: 'Name', type: 'text', required: true, maxLength: 10 }],
  },
  'major-subject-ssc-hsc': {
    routeKey: 'major-subject-ssc-hsc',
    apiPath: 'major-subject-ssc-hsc',
    idField: 'majorSubjectSscHscId',
    title: 'Major Subjects (SSC/HSC)',
    singularLabel: 'Major Subject (SSC/HSC)',
    icon: 'fa-solid fa-book',
    fields: [{ key: 'name', label: 'Name', type: 'text', required: true, maxLength: 100 }],
  },
  'major-subject-university': {
    routeKey: 'major-subject-university',
    apiPath: 'major-subject-university',
    idField: 'majorSubjectUniversityId',
    title: 'Major Subjects (University)',
    singularLabel: 'Major Subject (University)',
    icon: 'fa-solid fa-book-open',
    fields: [{ key: 'name', label: 'Name', type: 'text', required: true, maxLength: 150 }],
  },
  'special-category': {
    routeKey: 'special-category',
    apiPath: 'special-category',
    idField: 'specialCategoryId',
    title: 'Special Categories',
    singularLabel: 'Special Category',
    icon: 'fa-solid fa-star',
    fields: [{ key: 'name', label: 'Name', type: 'text', required: true, maxLength: 100 }],
  },
  'referral-source': {
    routeKey: 'referral-source',
    apiPath: 'referral-source',
    idField: 'referralSourceId',
    title: 'Referral Sources',
    singularLabel: 'Referral Source',
    icon: 'fa-solid fa-share-nodes',
    fields: [{ key: 'name', label: 'Name', type: 'text', required: true, maxLength: 100 }],
  },
};
