// Gender/MaritalStatus/Religion/BloodGroup options are no longer hardcoded here - they're
// dynamic admin-managed dropdowns loaded from the API (see PersonalInfoSectionComponent.ngOnInit).

// Common countries first (Bangladesh default, since candidates are overwhelmingly local),
// remainder alphabetical - a plain string list, not a backend enum, since nationality has no
// small fixed set the way Gender/Religion/BloodGroup do.
export const NationalityOptions = [
  'Bangladesh',
  'India',
  'Pakistan',
  'Nepal',
  'Bhutan',
  'Sri Lanka',
  'Myanmar',
  'Afghanistan',
  'Albania',
  'Algeria',
  'Argentina',
  'Australia',
  'Austria',
  'Bahrain',
  'Belgium',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Cambodia',
  'Canada',
  'China',
  'Colombia',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Egypt',
  'Estonia',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Germany',
  'Ghana',
  'Greece',
  'Hungary',
  'Iceland',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kuwait',
  'Laos',
  'Latvia',
  'Lebanon',
  'Libya',
  'Lithuania',
  'Luxembourg',
  'Malaysia',
  'Maldives',
  'Malta',
  'Mexico',
  'Mongolia',
  'Morocco',
  'Netherlands',
  'New Zealand',
  'Nigeria',
  'North Korea',
  'Norway',
  'Oman',
  'Palestine',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Saudi Arabia',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'South Africa',
  'South Korea',
  'Spain',
  'Sudan',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tanzania',
  'Thailand',
  'Turkey',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uzbekistan',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Other',
].map((name) => ({ label: name, value: name }));
