import { BloodGroupEnum, GenderEnum, MaritalStatusEnum, ReligionEnum } from '@app/@core/enums/recruitment.enum';

export const GenderOptions = [
  { label: 'Male', value: GenderEnum.Male },
  { label: 'Female', value: GenderEnum.Female },
  { label: 'Other', value: GenderEnum.Other },
];

export const MaritalStatusOptions = [
  { label: 'Single', value: MaritalStatusEnum.Single },
  { label: 'Married', value: MaritalStatusEnum.Married },
  { label: 'Other', value: MaritalStatusEnum.Other },
];

export const ReligionOptions = [
  { label: 'Islam', value: ReligionEnum.Islam },
  { label: 'Hinduism', value: ReligionEnum.Hinduism },
  { label: 'Christianity', value: ReligionEnum.Christianity },
  { label: 'Buddhism', value: ReligionEnum.Buddhism },
  { label: 'Other', value: ReligionEnum.Other },
];

export const BloodGroupOptions = [
  { label: 'A+', value: BloodGroupEnum.APositive },
  { label: 'A-', value: BloodGroupEnum.ANegative },
  { label: 'B+', value: BloodGroupEnum.BPositive },
  { label: 'B-', value: BloodGroupEnum.BNegative },
  { label: 'AB+', value: BloodGroupEnum.ABPositive },
  { label: 'AB-', value: BloodGroupEnum.ABNegative },
  { label: 'O+', value: BloodGroupEnum.OPositive },
  { label: 'O-', value: BloodGroupEnum.ONegative },
];

// Common countries first (Bangladesh default, since candidates are overwhelmingly local),
// remainder alphabetical - a plain string list, not a backend enum, since nationality has no
// small fixed set the way Gender/Religion/BloodGroup do.
export const NationalityOptions = [
  'Bangladesh',
  'India',
  'Pakistan',
  'Nepal',
  'Bhutan',
  'Sri Lanka',
  'Myanmar',
  'Afghanistan',
  'Albania',
  'Algeria',
  'Argentina',
  'Australia',
  'Austria',
  'Bahrain',
  'Belgium',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Cambodia',
  'Canada',
  'China',
  'Colombia',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Egypt',
  'Estonia',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Germany',
  'Ghana',
  'Greece',
  'Hungary',
  'Iceland',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kuwait',
  'Laos',
  'Latvia',
  'Lebanon',
  'Libya',
  'Lithuania',
  'Luxembourg',
  'Malaysia',
  'Maldives',
  'Malta',
  'Mexico',
  'Mongolia',
  'Morocco',
  'Netherlands',
  'New Zealand',
  'Nigeria',
  'North Korea',
  'Norway',
  'Oman',
  'Palestine',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Saudi Arabia',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'South Africa',
  'South Korea',
  'Spain',
  'Sudan',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tanzania',
  'Thailand',
  'Turkey',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uzbekistan',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Other',
].map((name) => ({ label: name, value: name }));
