import { IMenuItem } from '../interfaces/menuResponse.interface';
import { UserRoleEnum } from '../enums/user-role.enum';

export const webSidebarMenuItems: IMenuItem[] = [
  {
    href: '/dashboard',
    title: 'Dashboard',
    active: false,
    icon: 'fa-solid fa-chart-line',
    roles: [UserRoleEnum.Admin, UserRoleEnum.HR],
  },
  {
    title: 'Recruitment',
    active: false,
    icon: 'fa-solid fa-briefcase',
    roles: [UserRoleEnum.Admin, UserRoleEnum.HR],
    subItems: [
      {
        href: '/job-vacancy/job-vacancy-list',
        title: 'Job Vacancies',
        active: false,
        icon: 'fa-solid fa-list',
      },
      {
        href: '/hiring-pipeline/hiring-pipeline-list',
        title: 'Hiring Pipelines',
        active: false,
        icon: 'fa-solid fa-diagram-project',
      },
      {
        href: '/shortlist-filters/shortlist-filter-list',
        title: 'Shortlist Filters',
        active: false,
        icon: 'fa-solid fa-filter',
      },
      {
        href: '/candidate-recommendations/candidate-recommendation-list',
        title: 'Final Selection Recommendations',
        active: false,
        icon: 'fa-solid fa-star',
        roles: [UserRoleEnum.Admin],
      },
      {
        href: '/exam-questions/question-group-list',
        title: 'Question Groups',
        active: false,
        icon: 'fa-solid fa-layer-group',
      },
      {
        href: '/exam-questions/exam-question-list',
        title: 'Exam Questions',
        active: false,
        icon: 'fa-solid fa-circle-question',
      },
      {
        href: '/candidates',
        title: 'Candidates',
        active: false,
        icon: 'fa-solid fa-users',
      },
      {
        href: '/cv-bank',
        title: 'CV Bank',
        active: false,
        icon: 'fa-solid fa-magnifying-glass',
      },
      {
        href: '/talent-pools/talent-pool-list',
        title: 'Talent Pools',
        active: false,
        icon: 'fa-solid fa-user-group',
      },
      {
        href: '/applications',
        title: 'ATS Dashboard',
        active: false,
        icon: 'fa-solid fa-list-check',
      },
      {
        href: '/exam-venues/exam-venue-list',
        title: 'Exam Venues',
        active: false,
        icon: 'fa-solid fa-building',
      },
      {
        href: '/exams/exam-list',
        title: 'Exams',
        active: false,
        icon: 'fa-solid fa-file-pen',
      },
      {
        href: '/interview-venues/interview-venue-list',
        title: 'Interview Venues',
        active: false,
        icon: 'fa-solid fa-door-open',
      },
      {
        href: '/interviews/interview-list',
        title: 'Interviews',
        active: false,
        icon: 'fa-solid fa-people-arrows',
      },
    ],
  },
  {
    href: '/internal-jobs/job-list',
    title: 'Internal Job Board',
    active: false,
    icon: 'fa-solid fa-building',
  },
  {
    href: '/careers',
    title: 'Browse Careers',
    active: false,
    icon: 'fa-solid fa-magnifying-glass',
    roles: [UserRoleEnum.Candidate],
  },
  {
    href: '/candidate-profile',
    title: 'My Profile',
    active: false,
    icon: 'fa-solid fa-id-card',
    roles: [UserRoleEnum.Candidate],
  },
  {
    href: '/my-applications',
    title: 'My Applications',
    active: false,
    icon: 'fa-solid fa-list-check',
    roles: [UserRoleEnum.Candidate],
  },
  {
    href: '/account-settings',
    title: 'Account Settings',
    active: false,
    icon: 'fa-solid fa-user-gear',
  },
  {
    href: '/application-settings',
    title: 'Application Settings',
    active: false,
    icon: 'fa-solid fa-sliders',
    roles: [UserRoleEnum.Admin],
  },
  {
    title: 'System Administration',
    active: false,
    icon: 'fa-solid fa-gears',
    roles: [UserRoleEnum.Admin],
    subItems: [
      {
        href: '/master-data/country-list',
        title: 'Countries',
        active: false,
        icon: 'fa-solid fa-earth-asia',
      },
      {
        href: '/master-data/education-board-list',
        title: 'Education Boards',
        active: false,
        icon: 'fa-solid fa-landmark',
      },
      {
        href: '/master-data/degree-list',
        title: 'Degrees',
        active: false,
        icon: 'fa-solid fa-graduation-cap',
      },
      {
        href: '/master-data/university-list',
        title: 'Universities',
        active: false,
        icon: 'fa-solid fa-building-columns',
      },
      {
        href: '/master-data/gender-list',
        title: 'Genders',
        active: false,
        icon: 'fa-solid fa-venus-mars',
      },
      {
        href: '/master-data/marital-status-list',
        title: 'Marital Statuses',
        active: false,
        icon: 'fa-solid fa-ring',
      },
      {
        href: '/master-data/religion-list',
        title: 'Religions',
        active: false,
        icon: 'fa-solid fa-place-of-worship',
      },
      {
        href: '/master-data/major-subject-ssc-hsc-list',
        title: 'Major Subjects (SSC/HSC)',
        active: false,
        icon: 'fa-solid fa-book',
      },
      {
        href: '/master-data/major-subject-university-list',
        title: 'Major Subjects (University)',
        active: false,
        icon: 'fa-solid fa-book-open',
      },
      {
        href: '/master-data/blood-group-list',
        title: 'Blood Groups',
        active: false,
        icon: 'fa-solid fa-droplet',
      },
    ],
  },
];
